/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_final.vista;

/**
 *
 * @author ruppe
 */
public class Administracion extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public Administracion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pbarra = new javax.swing.JPanel();
        TBsalir = new javax.swing.JToggleButton();
        Pestudiante = new javax.swing.JPanel();
        Pfoto1 = new javax.swing.JPanel();
        Bestudiante = new javax.swing.JButton();
        Peleccion = new javax.swing.JPanel();
        Pfoto2 = new javax.swing.JPanel();
        Beleccion = new javax.swing.JButton();
        Peleccionvieja = new javax.swing.JPanel();
        Pgoto3 = new javax.swing.JPanel();
        Beleccionviejas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pbarra.setBackground(new java.awt.Color(153, 153, 153));

        TBsalir.setText("Salir");
        TBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PbarraLayout = new javax.swing.GroupLayout(Pbarra);
        Pbarra.setLayout(PbarraLayout);
        PbarraLayout.setHorizontalGroup(
            PbarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PbarraLayout.createSequentialGroup()
                .addContainerGap(599, Short.MAX_VALUE)
                .addComponent(TBsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        PbarraLayout.setVerticalGroup(
            PbarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PbarraLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(TBsalir)
                .addContainerGap())
        );

        Pestudiante.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout Pfoto1Layout = new javax.swing.GroupLayout(Pfoto1);
        Pfoto1.setLayout(Pfoto1Layout);
        Pfoto1Layout.setHorizontalGroup(
            Pfoto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        Pfoto1Layout.setVerticalGroup(
            Pfoto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );

        Bestudiante.setText("Cargar estudiante");
        Bestudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BestudianteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PestudianteLayout = new javax.swing.GroupLayout(Pestudiante);
        Pestudiante.setLayout(PestudianteLayout);
        PestudianteLayout.setHorizontalGroup(
            PestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PestudianteLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Bestudiante)
                    .addComponent(Pfoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        PestudianteLayout.setVerticalGroup(
            PestudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PestudianteLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Pfoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Bestudiante)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Peleccion.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout Pfoto2Layout = new javax.swing.GroupLayout(Pfoto2);
        Pfoto2.setLayout(Pfoto2Layout);
        Pfoto2Layout.setHorizontalGroup(
            Pfoto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        Pfoto2Layout.setVerticalGroup(
            Pfoto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );

        Beleccion.setText("Cargar elección");
        Beleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeleccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PeleccionLayout = new javax.swing.GroupLayout(Peleccion);
        Peleccion.setLayout(PeleccionLayout);
        PeleccionLayout.setHorizontalGroup(
            PeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeleccionLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Beleccion)
                    .addComponent(Pfoto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        PeleccionLayout.setVerticalGroup(
            PeleccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeleccionLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Pfoto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Beleccion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Peleccionvieja.setBackground(new java.awt.Color(204, 204, 204));
        Peleccionvieja.setPreferredSize(new java.awt.Dimension(216, 295));

        javax.swing.GroupLayout Pgoto3Layout = new javax.swing.GroupLayout(Pgoto3);
        Pgoto3.setLayout(Pgoto3Layout);
        Pgoto3Layout.setHorizontalGroup(
            Pgoto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        Pgoto3Layout.setVerticalGroup(
            Pgoto3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );

        Beleccionviejas.setText("Ver elecciones pasadas");
        Beleccionviejas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeleccionviejasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PeleccionviejaLayout = new javax.swing.GroupLayout(Peleccionvieja);
        Peleccionvieja.setLayout(PeleccionviejaLayout);
        PeleccionviejaLayout.setHorizontalGroup(
            PeleccionviejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeleccionviejaLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(PeleccionviejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Beleccionviejas)
                    .addComponent(Pgoto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        PeleccionviejaLayout.setVerticalGroup(
            PeleccionviejaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PeleccionviejaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Pgoto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Beleccionviejas)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pbarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pestudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Peleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Peleccionvieja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Pbarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Pestudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Peleccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Peleccionvieja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeleccionActionPerformed
        Cargar_Eleccion cargar_eleccion = new Cargar_Eleccion();
        cargar_eleccion.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_BeleccionActionPerformed

    private void BeleccionviejasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeleccionviejasActionPerformed
        Votaciones_Viejas votaciones_viejas = new Votaciones_Viejas();
        votaciones_viejas.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_BeleccionviejasActionPerformed

    private void TBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBsalirActionPerformed
        Index index = new Index();
        index.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_TBsalirActionPerformed

    private void BestudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BestudianteActionPerformed
        Cargar_Estudiante cargar_estudiante = new Cargar_Estudiante();
        cargar_estudiante.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_BestudianteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Beleccion;
    private javax.swing.JButton Beleccionviejas;
    private javax.swing.JButton Bestudiante;
    private javax.swing.JPanel Pbarra;
    private javax.swing.JPanel Peleccion;
    private javax.swing.JPanel Peleccionvieja;
    private javax.swing.JPanel Pestudiante;
    private javax.swing.JPanel Pfoto1;
    private javax.swing.JPanel Pfoto2;
    private javax.swing.JPanel Pgoto3;
    private javax.swing.JToggleButton TBsalir;
    // End of variables declaration//GEN-END:variables
}
