/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto_final.vista;

/**
 *
 * @author ruppe
 */
public class Cargar_Eleccion extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public Cargar_Eleccion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pbarra = new javax.swing.JPanel();
        TBsallir = new javax.swing.JToggleButton();
        Plistas = new javax.swing.JPanel();
        Pfoto1 = new javax.swing.JPanel();
        Bcargarlistas = new javax.swing.JButton();
        Pprevotacion = new javax.swing.JPanel();
        Pfoto2 = new javax.swing.JPanel();
        Bprevotacion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pbarra.setBackground(new java.awt.Color(153, 153, 153));

        TBsallir.setText("Volver");
        TBsallir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBsallirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PbarraLayout = new javax.swing.GroupLayout(Pbarra);
        Pbarra.setLayout(PbarraLayout);
        PbarraLayout.setHorizontalGroup(
            PbarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PbarraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TBsallir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        PbarraLayout.setVerticalGroup(
            PbarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PbarraLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(TBsallir)
                .addContainerGap())
        );

        Plistas.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout Pfoto1Layout = new javax.swing.GroupLayout(Pfoto1);
        Pfoto1.setLayout(Pfoto1Layout);
        Pfoto1Layout.setHorizontalGroup(
            Pfoto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        Pfoto1Layout.setVerticalGroup(
            Pfoto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );

        Bcargarlistas.setText("Cargar listas");
        Bcargarlistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcargarlistasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PlistasLayout = new javax.swing.GroupLayout(Plistas);
        Plistas.setLayout(PlistasLayout);
        PlistasLayout.setHorizontalGroup(
            PlistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlistasLayout.createSequentialGroup()
                .addGroup(PlistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlistasLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Pfoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PlistasLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(Bcargarlistas)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        PlistasLayout.setVerticalGroup(
            PlistasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlistasLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Pfoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Bcargarlistas)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        Pprevotacion.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout Pfoto2Layout = new javax.swing.GroupLayout(Pfoto2);
        Pfoto2.setLayout(Pfoto2Layout);
        Pfoto2Layout.setHorizontalGroup(
            Pfoto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        Pfoto2Layout.setVerticalGroup(
            Pfoto2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );

        Bprevotacion.setText("Ir a pre votación");
        Bprevotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BprevotacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PprevotacionLayout = new javax.swing.GroupLayout(Pprevotacion);
        Pprevotacion.setLayout(PprevotacionLayout);
        PprevotacionLayout.setHorizontalGroup(
            PprevotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PprevotacionLayout.createSequentialGroup()
                .addGroup(PprevotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PprevotacionLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Pfoto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PprevotacionLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(Bprevotacion)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        PprevotacionLayout.setVerticalGroup(
            PprevotacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PprevotacionLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Pfoto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Bprevotacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Pbarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(Plistas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(Pprevotacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Pbarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Plistas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pprevotacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BprevotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BprevotacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BprevotacionActionPerformed

    private void TBsallirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBsallirActionPerformed
        Index index = new Index();
        index.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_TBsallirActionPerformed

    private void BcargarlistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcargarlistasActionPerformed
        Cargar_Lista cargar_lista = new Cargar_Lista();
        cargar_lista.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_BcargarlistasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cargar_Eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cargar_Eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cargar_Eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cargar_Eleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cargar_Eleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bcargarlistas;
    private javax.swing.JButton Bprevotacion;
    private javax.swing.JPanel Pbarra;
    private javax.swing.JPanel Pfoto1;
    private javax.swing.JPanel Pfoto2;
    private javax.swing.JPanel Plistas;
    private javax.swing.JPanel Pprevotacion;
    private javax.swing.JToggleButton TBsallir;
    // End of variables declaration//GEN-END:variables
}
